GitHub action to run periodically or by trigger to extractor
checkstyle/test-configs pull request #160
Opened 2024-08-13 14:41 UTC by relentless-pursuit

Resolves #143

2024-08-13 14:41 UTC, relentless-pursuit commented
And, how to test this CI?

2024-08-13 15:35 UTC, romani requested changes
Create new workflow that will do only extract and commit

2024-08-15 00:41 UTC, relentless-pursuit commented
Testing of the workflow: https://github.com/checkstyle-gsoc/test-configs/actions/runs/10396815739

@Romani

2024-08-15 01:45 UTC, romani requested changes
Items

2024-08-15 01:45 UTC, romani commented on .github/workflows/ci.yml
> +name: Java CI and Automated Extraction
Separate workflow please

2024-09-01 21:25 UTC, closed without merging