Make changes in the extractor for the new workflow
checkstyle/test-configs pull request #163
Opened 2024-08-18 22:16 UTC by relentless-pursuit

Resolves #153

2024-08-18 23:58 UTC, romani commented
Please put in commit message exact reason of update, kind of summary of update

2024-08-19 00:45 UTC, relentless-pursuit commented
> Please put in commit message exact reason of update, kind of summary of update

Updated

2024-08-20 15:50 UTC, relentless-pursuit commented
@romani can we merge this. and release the extractor. i can then start testing the workflow on 5 scenarios i created before merging.

2024-08-20 20:52 UTC, romani requested changes
Items

2024-08-20 21:03 UTC, relentless-pursuit commented on extractor/src/main/java/com/example/extractor/CheckstyleExampleExtractor.java
> +            LOGGER.log(Level.SEVERE, "Error outputting default projects list", ex);
done

2024-08-20 21:11 UTC, merged