Refactor the project.properties list
checkstyle/test-configs pull request #165
Opened 2024-08-23 09:27 UTC by relentless-pursuit

Resolves #164

2024-08-23 16:05 UTC, romani commented
Please split into two commits, one in main change, second is results of generation.

In main change there should be change only to add two more lines, nothing else.

2024-08-25 13:24 UTC, relentless-pursuit commented
> Please split into two commits, one in main change, second is results of generation.
> 
> In main change there should be change only to add two more lines, nothing else.

done.

2024-08-25 13:30 UTC, relentless-pursuit commented
> Please split into two commits, one in main change, second is results of generation.
> 
> In main change there should be change only to add two more lines, nothing else.

Maybe, i copy pasted the entire proj.prop from that contribution. So, i had to just add the new projects?

2024-08-25 13:47 UTC, romani requested changes
please update /all-projects.properties too

items:

2024-08-25 13:47 UTC, romani commented on extractor/src/main/resources/list-of-projects.properties
> +checkstyle|git|https://github.com/checkstyle/checkstyle.git|master|
revert

2024-08-25 13:47 UTC, romani commented on extractor/src/main/resources/list-of-projects.properties
> +lombok-ast|git|https://github.com/rzwitserloot/lombok.ast|v0.2|
revert

2024-08-25 13:47 UTC, romani commented on extractor/src/main/resources/list-of-projects.properties
> +hibernate-orm|git|https://github.com/hibernate/hibernate-orm|4.2.19.Final|
revert

2024-08-25 13:47 UTC, romani commented on extractor/src/main/resources/list-of-projects.properties
> +apache-ant|git|https://github.com/apache/ant|ANT_194|
revert

2024-08-25 13:47 UTC, romani commented on extractor/src/main/resources/list-of-projects.properties
> +apache-struts|git|https://github.com/apache/struts.git|master|
revert

2024-09-02 19:44 UTC, closed without merging