testing git-diff
checkstyle/test-configs pull request #40
Opened 2024-06-19 07:42 UTC by relentless-pursuit

Part of #1

2024-06-19 07:45 UTC, relentless-pursuit commented
I have been reading about this CI command added git-diff, but struggle to understand. To my understanding, CI checks out my PR and compares the changes with the latest code available on remote. And, if any untracked changes, then it will fail. For instance, i have untracked changes in this PR in my local. But, the job seems to succeed.

2024-06-19 14:28 UTC, romani commented
https://github.com/checkstyle/test-configs/actions/runs/9578108855/job/26407651096?pr=40#step:5:204

test is not failed, even it is crashed with exception and produced no output.

I checked it on local, no diff on local.
diff check works.

2024-06-19 14:38 UTC, romani commented
you will improve at scope of this issue - https://github.com/checkstyle/test-configs/issues/41

2024-06-20 16:46 UTC, romani commented
@relentless-pursuit , please rebase

2024-06-21 17:16 UTC, relentless-pursuit commented
Rebased. But, i am not sure how this git diff works? Shouldn't the job be pointing to new files added liek clone the latest checkstyle test-config and compare with the PR?

2024-06-22 00:00 UTC, romani commented
No, it just do git status on PR code after execution

2024-06-22 11:58 UTC, relentless-pursuit commented
> No, it just do git status on PR code after execution.
> 
> Create new file in git repository from test execution and it should be caught

yes, i did. but, i guess i didn't see any failure. i created a folder from mainslaunchertest.java and then i first kept them in unstaged. but, the job didn't fail. then in the next commit, i put them in the staging and did commit.

2024-06-22 13:22 UTC, romani commented
New empty folder is not status changed for git, please create file

2024-06-22 13:24 UTC, romani requested changes
Item

2024-06-22 13:24 UTC, romani commented on AbstractClassName/Example1/config.xml
> +<!DOCTYPE module PUBLIC
Remove from commit this folder and it should be caught

2024-06-22 13:41 UTC, relentless-pursuit commented
> New empty folder is not status changed for git, please create file

I had actually created a complete folder with config.xml. Except, i didn't commit but kept in unstaged env. Yes, i will act on the review and test again.

2024-06-23 19:46 UTC, romani commented
It works, see it here https://github.com/checkstyle/test-configs/actions/runs/9635984919/job/26573394995?pr=53#step:6:30

I think you can close this PR

2024-06-23 19:54 UTC, relentless-pursuit commented
Closing the PR as testing is validated.

2024-06-23 19:54 UTC, closed without merging